DISABLE:
  - SPELL
DISABLE_LINTERS:
  # We prefer jq automatic formatting for JSON & YAML
  - JSON_PRETTIER
  - YAML_PRETTIER
  - HTML_HTMLHINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  # The scope of this tool is too wide, I prefer the other linters already present.
  - REPOSITORY_DEVSKIM
  # Buggy
  - REPOSITORY_OSV_SCANNER
ACTION_ZIZMOR_ARGUMENTS: >-
  --min-severity high
ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
MAKEFILE_CHECKMAKE_FILTER_REGEX_EXCLUDE: content/post/story-first-makefile/.*
REPOSITORY_KICS_ARGUMENTS: --fail-on=high
